// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUpo-9lbTdIKDd76TTfWwS8CRUWOuJAA0',
    appId: '1:659283496028:web:8777897ccf8fcf9bb1ea99',
    messagingSenderId: '659283496028',
    projectId: 'notes-78f4c',
    authDomain: 'notes-78f4c.firebaseapp.com',
    storageBucket: 'notes-78f4c.firebasestorage.app',
    measurementId: 'G-M4G1WF19BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyzWao6peGqHCi8g0eADepN8yvU3dEJsU',
    appId: '1:659283496028:android:3a302ee4c108ab4db1ea99',
    messagingSenderId: '659283496028',
    projectId: 'notes-78f4c',
    storageBucket: 'notes-78f4c.firebasestorage.app',
  );

}